const express=require('express');
const auth=require('../controllers/adminAuthController');
const products=require('../controllers/adminProductController');
const categories=require('../controllers/adminCategoryController');
const orders=require('../controllers/adminOrderController');
const Product=require('../models/Product');
const Category=require('../models/Category');
const Order=require('../models/Order');
const {requireAdmin}=require('../middleware/auth');
const {requireCsrf}=require('../middleware/csrf');
const {upload}=require('../services/imageService');
const router=express.Router();
router.get('/',auth.adminRoot);
router.get('/setup',auth.setupPage); router.post('/setup',auth.setup);
router.get('/login',auth.loginPage); router.post('/login',auth.login);
router.post('/logout',requireAdmin,auth.logout);
router.use(requireAdmin);
router.get('/dashboard',async(req,res,next)=>{try{const [productsCount,categoriesCount,ordersCount]=await Promise.all([Product.countDocuments(),Category.countDocuments(),Order.countDocuments()]);res.render('admin/dashboard',{productsCount,categoriesCount,ordersCount});}catch(e){next(e);}});
router.get('/products',products.list); router.get('/products/new',products.newPage); router.get('/products/:id/edit',products.editPage);
router.post('/products',upload.array('images',4),requireCsrf,products.create);
router.post('/products/:id',upload.array('images',4),requireCsrf,products.update);
router.post('/products/:id/delete',products.remove);
router.get('/categories',categories.page); router.post('/categories',categories.create); router.post('/categories/:id',categories.update); router.post('/categories/:id/delete',categories.remove);
router.get('/orders',orders.list); router.get('/orders/:id',orders.detail); router.post('/orders/:id/status',orders.updateStatus);
module.exports=router;
