const Product = require('../models/Product');
const Category = require('../models/Category');
const { slugify, cleanText } = require('../utils/text');
const { saveImages, deleteImages } = require('../services/imageService');
async function uniqueSlug(name, ignoreId = null) {
  const base = slugify(name) || `product-${Date.now()}`;
  let slug = base, n = 2;
  while (await Product.exists({ slug, ...(ignoreId ? { _id: { $ne: ignoreId } } : {}) })) slug = `${base}-${n++}`;
  return slug;
}
function values(body) { return { name: body.name || '', description: body.description || '', price: body.price || '', stock: body.stock || '', category: body.category || '' }; }
async function list(req, res, next) { try { const products = await Product.find().populate('category').sort({ createdAt: -1 }).lean(); res.render('admin/products', { products }); } catch (e) { next(e); } }
async function newPage(req, res, next) { try { const categories = await Category.find().sort({ name: 1 }).lean(); res.render('admin/product-form', { mode:'create', product:null, categories, error:'', values:{} }); } catch(e){next(e);} }
async function editPage(req, res, next) { try { const [product,categories]=await Promise.all([Product.findById(req.params.id).lean(),Category.find().sort({name:1}).lean()]); if(!product) return res.status(404).send('Product not found.'); res.render('admin/product-form',{mode:'edit',product,categories,error:'',values:product}); } catch(e){next(e);} }
function validate(body) { const name=cleanText(body.name,120), description=cleanText(body.description,5000), price=Number(body.price), stock=Number(body.stock), category=String(body.category||''); if(!name) return {error:'Product name is required.'}; if(!description) return {error:'Product description is required.'}; if(!Number.isFinite(price)||price<=0) return {error:'Price must be greater than 0.'}; if(!Number.isInteger(stock)||stock<0) return {error:'Stock must be a non-negative whole number.'}; if(!category) return {error:'Category is required.'}; return {data:{name,description,price,stock,category}}; }
async function create(req,res,next){ let saved=[]; try{ const categories=await Category.find().sort({name:1}).lean(); const check=validate(req.body); if(check.error) return res.status(400).render('admin/product-form',{mode:'create',product:null,categories,error:check.error,values:values(req.body)}); if(!(await Category.exists({_id:check.data.category}))) return res.status(400).render('admin/product-form',{mode:'create',product:null,categories,error:'Selected category does not exist.',values:values(req.body)}); saved=await saveImages(req.files||[]); const product=await Product.create({...check.data,slug:await uniqueSlug(check.data.name),images:saved}); res.redirect(`/admin/products/${product._id}/edit?created=1`); }catch(e){ if(saved.length) await deleteImages(saved); next(e);} }
async function update(req,res,next){ let added=[]; try{ const product=await Product.findById(req.params.id); if(!product) return res.status(404).send('Product not found.'); const categories=await Category.find().sort({name:1}).lean(); const check=validate(req.body); if(check.error) return res.status(400).render('admin/product-form',{mode:'edit',product:product.toObject(),categories,error:check.error,values:values(req.body)}); if(!(await Category.exists({_id:check.data.category}))) return res.status(400).render('admin/product-form',{mode:'edit',product:product.toObject(),categories,error:'Selected category does not exist.',values:values(req.body)}); const remove=Array.isArray(req.body.removeImages)?req.body.removeImages:[req.body.removeImages].filter(Boolean); const kept=product.images.filter(x=>!remove.includes(x)); if(kept.length+(req.files||[]).length>4) return res.status(400).render('admin/product-form',{mode:'edit',product:product.toObject(),categories,error:'A product can have at most 4 images.',values:values(req.body)}); added=await saveImages(req.files||[]); Object.assign(product,check.data,{slug:await uniqueSlug(check.data.name,product._id),images:[...kept,...added]}); await product.save(); await deleteImages(remove); res.redirect(`/admin/products/${product._id}/edit?saved=1`); }catch(e){if(added.length) await deleteImages(added); next(e);} }
async function remove(req,res,next){try{const product=await Product.findByIdAndDelete(req.params.id); if(product) await deleteImages(product.images); res.redirect('/admin/products');}catch(e){next(e);} }
module.exports={list,newPage,editPage,create,update,remove};
