const crypto = require('crypto');
const Product = require('../models/Product');
const Order = require('../models/Order');
const Category = require('../models/Category');
const { cleanText } = require('../utils/text');
function fail(status,message){const e=new Error(message);e.statusCode=status;e.expose=true;throw e;}
async function makeOrderNumber(){for(let i=0;i<5;i++){const d=new Date();const date=`${String(d.getFullYear()).slice(-2)}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;const n=`F-${date}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;if(!(await Order.exists({orderNumber:n})))return n;}return `F-${Date.now()}`;}
async function create(req,res,next){const adjusted=[];try{const raw=Array.isArray(req.body.cartItems)?req.body.cartItems:[];if(!raw.length)fail(400,'Your cart is empty.');if(raw.length>50)fail(400,'Too many different items in one order.');const grouped=new Map();for(const item of raw){const id=String(item.id||item.productId||'');const qty=Math.max(1,Math.min(99,Number(item.qty)||1));if(!id.match(/^[a-f0-9]{24}$/i))fail(400,'Invalid product in cart.');grouped.set(id,Math.min(99,(grouped.get(id)||0)+qty));}const products=await Product.find({_id:{$in:[...grouped.keys()]}}).lean();if(products.length!==grouped.size)fail(400,'One or more products are no longer available.');const items=[];let subtotal=0;for(const p of products){const qty=grouped.get(String(p._id));if(p.stock<qty)fail(409,`${p.name} only has ${p.stock} item(s) left.`);items.push({productId:p._id,name:p.name,image:p.images?.[0]||'',price:Number(p.price),qty});subtotal+=Number(p.price)*qty;}const first=cleanText(req.body.firstName,80),last=cleanText(req.body.lastName,80),phone=cleanText(req.body.phone,40),email=cleanText(req.body.email,254).toLowerCase(),address=cleanText(req.body.address,500),city=cleanText(req.body.city,100),postalCode=cleanText(req.body.postalCode,30),notes=cleanText(req.body.notes,1000),paymentMethod=String(req.body.paymentMethod||'cod');if(!first||!last||!phone||!address||!city)fail(400,'Name, phone, address and city are required.');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Enter a valid email address.');if(!['cod','manual'].includes(paymentMethod))fail(400,'Invalid payment method.');for(const item of items){const updated=await Product.findOneAndUpdate({_id:item.productId,stock:{$gte:item.qty}},{$inc:{stock:-item.qty}},{new:true});if(!updated){for(const done of adjusted)await Product.updateOne({_id:done.productId},{$inc:{stock:done.qty}});fail(409,`${item.name} no longer has enough stock.`);}adjusted.push(item);}let order;try{order=await Order.create({orderNumber:await makeOrderNumber(),customerName:`${first} ${last}`,phone,email,address,city,postalCode,notes,items,subtotal,total:subtotal,paymentMethod});}catch(e){for(const done of adjusted)await Product.updateOne({_id:done.productId},{$inc:{stock:done.qty}});throw e;}req.session.completedOrders=[...(req.session.completedOrders||[]).slice(-9),order.orderNumber];res.status(201).json({success:true,orderId:order.orderNumber,total:order.total});}catch(e){next(e);}}
async function complete(req,res,next){try{const id=String(req.query.id||'');const categories=await Category.find().sort({name:1}).lean();if(!id||(req.session.completedOrders||[]).indexOf(id)===-1)return res.status(404).render('public/pages/not-found',{categories,pageTitle:'Order not found',metaDescription:'Order not found.'});const order=await Order.findOne({orderNumber:id}).lean();if(!order)return res.status(404).render('public/pages/not-found',{categories,pageTitle:'Order not found',metaDescription:'Order not found.'});res.set('X-Robots-Tag','noindex, nofollow');res.render('public/pages/order-complete',{categories,order,pageTitle:'Order received — FORME',metaDescription:'Your order has been received.'});}catch(e){next(e);}}
module.exports={create,complete};
